language: php
php:
  - '7.1.8'
branches:
  only:
    master
before_install:
  - cp .env.example .env
  - travis_retry composer self-update
  - composer install
  - php artisan key:generate
script: phpunit --bootstrap vendor/autoload.php tests
